# Homework

In [221]:
import pandas as pd

### Energy Usage data

Let's analyze a few decades of <a href="https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/global_emissions.csv">CO2 emissions data</a> taken <a href="https://essd.copernicus.org/articles/12/1437/2020/">from Earth System Science Data (ESSD)</a>.

This data spans several centuries, but is mostly incomplete for most countries until the 1970s.

In [222]:
## read data
emissions_df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/global_emissions.csv")
emissions_df

                        Country  Year   fuel  emissions
0                   Afghanistan  1750   Coal        NaN
1                   Afghanistan  1751   Coal        NaN
2                   Afghanistan  1752   Coal        NaN
3                   Afghanistan  1753   Coal        NaN
4                   Afghanistan  1754   Coal        NaN
...                         ...   ...    ...        ...
378619                    Yemen  2021  Other        NaN
378620                   Zambia  2021  Other        NaN
378621                 Zimbabwe  2021  Other        NaN
378622  International Transport  2021  Other        NaN
378623                   Global  2021  Other   0.037443

[378624 rows x 4 columns]

## Interview the energy data

A few things to know. The `emissions` column show CO2 emmissions per capita per year. So it is normalized to account for geogrphic size.

Because the emissions were almost all generated by colonial powers till the late 1950s, you should filter out any data prior to 1980. In other words, do all of the following with data from 1980 onwards.

#### Your homework, specifically:

Code the answers to **SIX questions** that you come up with. In otherwords, write the Pandas code needed to answer questions that you want to answer.

Of the **Six questions**:

- Answer **Four** questions **WITHOUT** using AI.
- Answer **TWO** questions **using AI**, if you want.

In [223]:
### create cells as necessary

In [224]:
emissions_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 378624 entries, 0 to 378623
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Country    378624 non-null  str
 1   Year       378624 non-null  int64
 2   fuel       378624 non-null  str
 3   emissions  85201 non-null   float64
dtypes: float64(1), int64(1), str(2)
memory usage: 11.6 MB

In [225]:
emissions_trim = emissions_df[emissions_df["Year"] >= 1980]
emissions_trim

                        Country  Year   fuel  emissions
72880               Afghanistan  1980   Coal   0.025288
72881                   Albania  1980   Coal   0.789684
72882                   Algeria  1980   Coal   0.085835
72883                   Andorra  1980   Coal        NaN
72884                    Angola  1980   Coal   0.000000
...                         ...   ...    ...        ...
378619                    Yemen  2021  Other        NaN
378620                   Zambia  2021  Other        NaN
378621                 Zimbabwe  2021  Other        NaN
378622  International Transport  2021  Other        NaN
378623                   Global  2021  Other   0.037443

[58464 rows x 4 columns]

In [226]:
emissions_trim.info()

<class 'pandas.DataFrame'>
Index: 58464 entries, 72880 to 378623
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    58464 non-null  str
 1   Year       58464 non-null  int64
 2   fuel       58464 non-null  str
 3   emissions  46570 non-null  float64
dtypes: float64(1), int64(1), str(2)
memory usage: 2.2 MB

### Q1: What country has emitted the most per capita CO2 in 2021 using one fuel type?

In [227]:
emissions_trim['Year'].max()

np.int64(2021)

In [228]:
df_2021 = emissions_trim.query("Year == 2021")
df_2021

                        Country  Year   fuel  emissions
371512              Afghanistan  2021   Coal   0.104828
371513                  Albania  2021   Coal   0.061096
371514                  Algeria  2021   Coal   0.024798
371515                  Andorra  2021   Coal   0.000000
371516                   Angola  2021   Coal   0.000000
...                         ...   ...    ...        ...
378619                    Yemen  2021  Other        NaN
378620                   Zambia  2021  Other        NaN
378621                 Zimbabwe  2021  Other        NaN
378622  International Transport  2021  Other        NaN
378623                   Global  2021  Other   0.037443

[1392 rows x 4 columns]

In [229]:
max_2021 = df_2021['emissions'].max()
max_2021

np.float64(31.072901)

In [230]:
most_2021 = df_2021.query("emissions == @max_2021")
most_2021

       Country  Year fuel  emissions
374781   Qatar  2021  Gas  31.072901

In [231]:
print(f"The country that produced the most per capita CO2 emissions from a single fuel type in 2021 was Qatar.")

The country that produced the most per capita CO2 emissions from a single fuel type in 2021 was Qatar.

### Q2: What country emitted the least CO2 across all years documented?

In [232]:
country_totals = emissions_trim.groupby("Country", as_index=False)["emissions"].sum()

In [233]:
country_totals['emissions'].min()

np.float64(0.0)

In [234]:
country_totals.query("emissions == 0.0")

                      Country  emissions
6                  Antarctica        0.0
42           Christmas Island        0.0
70   French Equatorial Africa        0.0
73         French West Africa        0.0
95    International Transport        0.0
109         Kuwaiti Oil Fires        0.0
114           Leeward Islands        0.0
157   Pacific Islands (Palau)        0.0
161         Panama Canal Zone        0.0
168               Puerto Rico        0.0
173            Ryukyu Islands        0.0
198  St. Kitts-Nevis-Anguilla        0.0

### Q3: How much CO2 emission per capita was documented across all countries per year?

In [235]:
year_totals = emissions_trim.groupby("Year", as_index=False)["emissions"].sum()
year_totals

    Year    emissions
0   1980  1155.961539
1   1981  1062.524030
2   1982  1051.056204
3   1983   944.917491
4   1984  1073.207185
5   1985  1121.932960
6   1986   955.007228
7   1987   951.239254
8   1988   980.987511
9   1989  1027.694595
10  1990  1050.695107
11  1991  1024.417086
12  1992  1026.508784
13  1993  1055.983125
14  1994  1044.616509
15  1995  1028.342831
16  1996  1038.696324
17  1997  1043.374279
18  1998   982.698891
19  1999   990.557403
20  2000  1072.593221
21  2001  1083.027471
22  2002  1088.154002
23  2003  1119.613625
24  2004  1141.621559
25  2005  1147.869341
26  2006  1161.074575
27  2007  1174.368621
28  2008  1169.904990
29  2009  1113.218990
30  2010  1131.714117
31  2011  1132.497934
32  2012  1134.028190
33  2013  1103.973526
34  2014  1101.431342
35  2015  1089.943089
36  2016  1071.378512
37  2017  1076.098470
38  2018  1068.217620
39  2019  1051.535670
40  2020   980.572048
41  2021  1015.698876

### Q4: What year had the most CO2 emissions per capita across all countries and fuel types?

In [236]:
year_totals['emissions'].max()

np.float64(1174.368621)

In [237]:
year_totals.query("emissions == 1373.15072")

Empty DataFrame
Columns: [Year, emissions]
Index: []

In [238]:
print(f"1956 had the most emissions per capita, according to the dataset.")

1956 had the most emissions per capita, according to the dataset.

### Q5: What year had the fewest CO2 emissions per capita across all countries and fuel types?

In [239]:
year_totals['emissions'].min()

np.float64(944.917491)

In [240]:
year_totals.query("emissions == 0.011249")

Empty DataFrame
Columns: [Year, emissions]
Index: []

In [241]:
print(f"1755 had the most emissions per capita, according to the dataset.")

1755 had the most emissions per capita, according to the dataset.

### Q6: What fuel type produced the most CO2 emissions per capita?

In [242]:
fuel_totals = emissions_trim.groupby("fuel", as_index=False)["emissions"].sum()
fuel_totals

      fuel     emissions
0   Cement    902.564298
1     Coal   8162.561166
2  Flaring    926.335983
3      Gas   9763.547307
4      Oil  24946.882868
5    Other    137.062503

In [243]:
fuel_totals['emissions'].max()

np.float64(24946.882868)

In [244]:
fuel_totals.query("emissions == 24946.882868")

  fuel     emissions
4  Oil  24946.882868

In [245]:
print(f"The most per capita CO2 emissions were caused by oil.")

The most per capita CO2 emissions were caused by oil.